exports.getHelpers = (req, res) => {
    const helpers = [
      { id: 1, title: 'Marie Curie Helper London', description: 'Someone to have a chat with over a cup of tea, help you get to an appointment or run an errand, or just be there to listen when you need a friendly ear. Companion volunteers can be there for you for exactly these things. Once we’ve got to know a little bit about you, your interests and your needs, we’ll match you with a trained, dedicated volunteer. They’ll spend up to three hours a week visiting you at home or talking with you over the phone. It’s up to you how you spend your time with your companion – you might just want to chat or there might be something practical your volunteer can help you with. The service is entirely based around your needs.', phone: '0201234567', isOpen: true, region: 'London', date: "2024-12-31"},
      { id: 2, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 3, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 4, title: 'Marie Curie Helper London', description: 'Someone to have a chat with over a cup of tea, help you get to an appointment or run an errand, or just be there to listen when you need a friendly ear. Companion volunteers can be there for you for exactly these things. Once we’ve got to know a little bit about you, your interests and your needs, we’ll match you with a trained, dedicated volunteer. They’ll spend up to three hours a week visiting you at home or talking with you over the phone. It’s up to you how you spend your time with your companion – you might just want to chat or there might be something practical your volunteer can help you with. The service is entirely based around your needs.', phone: '0201234567', isOpen: true, region: 'London', date: "2024-12-31"},
      { id: 5, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 6, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 7, title: 'Marie Curie Helper London', description: 'Someone to have a chat with over a cup of tea, help you get to an appointment or run an errand, or just be there to listen when you need a friendly ear. Companion volunteers can be there for you for exactly these things. Once we’ve got to know a little bit about you, your interests and your needs, we’ll match you with a trained, dedicated volunteer. They’ll spend up to three hours a week visiting you at home or talking with you over the phone. It’s up to you how you spend your time with your companion – you might just want to chat or there might be something practical your volunteer can help you with. The service is entirely based around your needs.', phone: '0201234567', isOpen: true, region: 'London', date: "2024-12-31"},
      { id: 8, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 9, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 10, title: 'Marie Curie Helper London', description: 'Someone to have a chat with over a cup of tea, help you get to an appointment or run an errand, or just be there to listen when you need a friendly ear. Companion volunteers can be there for you for exactly these things. Once we’ve got to know a little bit about you, your interests and your needs, we’ll match you with a trained, dedicated volunteer. They’ll spend up to three hours a week visiting you at home or talking with you over the phone. It’s up to you how you spend your time with your companion – you might just want to chat or there might be something practical your volunteer can help you with. The service is entirely based around your needs.', phone: '0201234567', isOpen: true, region: 'London', date: "2024-12-31"},
      { id: 11, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
      { id: 12, title: 'Marie Curie Helper Manchester', description: 'Help for Manchester', phone: '0161123456', isOpen: false, region: 'Manchester', date: "2024-12-20"},
    ];
    res.json(helpers);
};